<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Kobbyist.ProgressionControls.Core</RootNamespace>
    <AssemblyName>Kobbyist.ProgressionControls.Core</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>

